#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
echo `date` > last-run-started

# Presumed to be running from find-releases git dir...
git fetch origin
git checkout origin/master

# ... that's next to a chromium src tree named 'cr-find-rel'.
cd ../cr-find-rel/src
git fetch origin
git fetch --tags
git checkout origin/master

# ... with depot_tools in the path.
# We don't want this -- remotes/branch-heads will cause name-rev to be assigned
# to those branches, rather than release tags.
# gclient sync --with_branch_heads --nohooks

# git name-rev sort of sucks at large-ish repos? Or the weird svn merge thing
# we did circa 2014? Not sure. This avoids the problem though.
ulimit -s unlimited

# ... output is stored beside both of those.
python2 ../../find-releases/build_hash_to_release_map2.py ../../find-releases-output
python2 ../../find-releases/gen_static.py ../../find-releases-output/cache.pickle ../../find-releases-output/static

# ... and we need the cloud sdk for gsutil.
cd ../../find-releases-output/static
gsutil -m rsync -d -r . gs://chromium-find-releases-static/

cd $DIR
echo `date` > last-run-finished
